# Generated by Django 4.2.3 on 2023-07-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('href', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StatsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.CharField(max_length=50)),
                ('center_text', models.CharField(max_length=50)),
                ('bottom_text', models.CharField(max_length=50)),
                ('direction', models.CharField(max_length=25)),
            ],
        ),
    ]
